server:
  port: 2000
---
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 5000
welcomeMSG: Hello from Prod
---
spring:
  config:
    activate:
      on-profile: test
server:
  port: 4000
welcomeMSG: Hello from Test